on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 11
        cache: gradle
    - name: prepare
      run: |
        git clone https://github.com/LlemonDuck/tombs-of-amascut.git
    - name: build
      run: |
        pushd ./tombs-of-amascut
          ./gradlew build
        popd
        mkdir -p /tmp/jars
        cp ./tombs-of-amascut/build/libs/* /tmp/jars
    - uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'pull_request' }}
      with:
        name: jars
        path: /tmp/jars
        retention-days: 1
